"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConnectionParamsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ConnectionParamsRequest = ConnectionParamsRequest

@typing.final
class ConnectionParamsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DIAL_URI_FIELD_NUMBER: builtins.int
    CONTRACT_ADDRESS_FIELD_NUMBER: builtins.int
    dial_uri: builtins.str
    contract_address: builtins.str
    def __init__(
        self,
        *,
        dial_uri: builtins.str = ...,
        contract_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["contract_address", b"contract_address", "dial_uri", b"dial_uri"]) -> None: ...

global___ConnectionParamsResponse = ConnectionParamsResponse

@typing.final
class IPCBucketCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___IPCBucketCreateRequest = IPCBucketCreateRequest

@typing.final
class IPCBucketCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "name", b"name"]) -> None: ...

global___IPCBucketCreateResponse = IPCBucketCreateResponse

@typing.final
class IPCBucketViewRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    name: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "name", b"name"]) -> None: ...

global___IPCBucketViewRequest = IPCBucketViewRequest

@typing.final
class IPCBucketViewResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    """todo: remove this when contract removes id from deleteBucket endpoint"""
    name: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "id", b"id", "name", b"name"]) -> None: ...

global___IPCBucketViewResponse = IPCBucketViewResponse

@typing.final
class IPCBucketListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    address: builtins.str
    def __init__(
        self,
        *,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address"]) -> None: ...

global___IPCBucketListRequest = IPCBucketListRequest

@typing.final
class IPCBucketListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class IPCBucket(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        CREATED_AT_FIELD_NUMBER: builtins.int
        name: builtins.str
        @property
        def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "name", b"name"]) -> None: ...

    BUCKETS_FIELD_NUMBER: builtins.int
    @property
    def buckets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IPCBucketListResponse.IPCBucket]: ...
    def __init__(
        self,
        *,
        buckets: collections.abc.Iterable[global___IPCBucketListResponse.IPCBucket] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["buckets", b"buckets"]) -> None: ...

global___IPCBucketListResponse = IPCBucketListResponse

@typing.final
class IPCBucketDeleteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IPCBucketDeleteRequest = IPCBucketDeleteRequest

@typing.final
class IPCBucketDeleteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IPCBucketDeleteResponse = IPCBucketDeleteResponse

@typing.final
class IPCChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Block(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CID_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        cid: builtins.str
        size: builtins.int
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            size: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["cid", b"cid", "size", b"size"]) -> None: ...

    CID_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    BLOCKS_FIELD_NUMBER: builtins.int
    cid: builtins.str
    index: builtins.int
    size: builtins.int
    @property
    def blocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IPCChunk.Block]: ...
    def __init__(
        self,
        *,
        cid: builtins.str = ...,
        index: builtins.int = ...,
        size: builtins.int = ...,
        blocks: collections.abc.Iterable[global___IPCChunk.Block] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blocks", b"blocks", "cid", b"cid", "index", b"index", "size", b"size"]) -> None: ...

global___IPCChunk = IPCChunk

@typing.final
class IPCFileUploadChunkCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHUNK_FIELD_NUMBER: builtins.int
    BUCKET_ID_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    bucket_id: builtins.bytes
    file_name: builtins.str
    @property
    def chunk(self) -> global___IPCChunk: ...
    def __init__(
        self,
        *,
        chunk: global___IPCChunk | None = ...,
        bucket_id: builtins.bytes = ...,
        file_name: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["chunk", b"chunk"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bucket_id", b"bucket_id", "chunk", b"chunk", "file_name", b"file_name"]) -> None: ...

global___IPCFileUploadChunkCreateRequest = IPCFileUploadChunkCreateRequest

@typing.final
class IPCFileUploadChunkCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class BlockUpload(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CID_FIELD_NUMBER: builtins.int
        NODE_ADDRESS_FIELD_NUMBER: builtins.int
        NODE_ID_FIELD_NUMBER: builtins.int
        PERMIT_FIELD_NUMBER: builtins.int
        cid: builtins.str
        node_address: builtins.str
        node_id: builtins.str
        permit: builtins.str
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            node_address: builtins.str = ...,
            node_id: builtins.str = ...,
            permit: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["cid", b"cid", "node_address", b"node_address", "node_id", b"node_id", "permit", b"permit"]) -> None: ...

    BLOCKS_FIELD_NUMBER: builtins.int
    @property
    def blocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IPCFileUploadChunkCreateResponse.BlockUpload]: ...
    def __init__(
        self,
        *,
        blocks: collections.abc.Iterable[global___IPCFileUploadChunkCreateResponse.BlockUpload] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blocks", b"blocks"]) -> None: ...

global___IPCFileUploadChunkCreateResponse = IPCFileUploadChunkCreateResponse

@typing.final
class IPCFileBlockDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSACTION_FIELD_NUMBER: builtins.int
    @property
    def transaction(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        transaction: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["transaction", b"transaction"]) -> None: ...

global___IPCFileBlockDataRequest = IPCFileBlockDataRequest

@typing.final
class IPCFileBlockData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    CID_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    CHUNK_FIELD_NUMBER: builtins.int
    BUCKET_ID_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    cid: builtins.str
    """only present in first msg of request stream"""
    index: builtins.int
    """only present in first msg of request stream"""
    bucket_id: builtins.bytes
    file_name: builtins.str
    @property
    def chunk(self) -> global___IPCChunk:
        """only present in first msg of request stream"""

    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        cid: builtins.str = ...,
        index: builtins.int = ...,
        chunk: global___IPCChunk | None = ...,
        bucket_id: builtins.bytes = ...,
        file_name: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["chunk", b"chunk"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bucket_id", b"bucket_id", "chunk", b"chunk", "cid", b"cid", "data", b"data", "file_name", b"file_name", "index", b"index"]) -> None: ...

global___IPCFileBlockData = IPCFileBlockData

@typing.final
class IPCFileUploadBlockResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IPCFileUploadBlockResponse = IPCFileUploadBlockResponse

@typing.final
class IPCFileViewRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "bucket_name", b"bucket_name", "file_name", b"file_name"]) -> None: ...

global___IPCFileViewRequest = IPCFileViewRequest

@typing.final
class IPCFileViewResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    ROOT_CID_FIELD_NUMBER: builtins.int
    ENCODED_SIZE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    root_cid: builtins.str
    encoded_size: builtins.int
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        root_cid: builtins.str = ...,
        encoded_size: builtins.int = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "created_at", b"created_at", "encoded_size", b"encoded_size", "file_name", b"file_name", "root_cid", b"root_cid"]) -> None: ...

global___IPCFileViewResponse = IPCFileViewResponse

@typing.final
class IPCFileDownloadCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "bucket_name", b"bucket_name", "file_name", b"file_name"]) -> None: ...

global___IPCFileDownloadCreateRequest = IPCFileDownloadCreateRequest

@typing.final
class IPCFileDownloadCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Chunk(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CID_FIELD_NUMBER: builtins.int
        ENCODED_SIZE_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        cid: builtins.str
        encoded_size: builtins.int
        size: builtins.int
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            encoded_size: builtins.int = ...,
            size: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["cid", b"cid", "encoded_size", b"encoded_size", "size", b"size"]) -> None: ...

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    CHUNKS_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    @property
    def chunks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IPCFileDownloadCreateResponse.Chunk]: ...
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        chunks: collections.abc.Iterable[global___IPCFileDownloadCreateResponse.Chunk] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "chunks", b"chunks"]) -> None: ...

global___IPCFileDownloadCreateResponse = IPCFileDownloadCreateResponse

@typing.final
class IPCFileDownloadChunkCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    CHUNK_CID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    chunk_cid: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        chunk_cid: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "bucket_name", b"bucket_name", "chunk_cid", b"chunk_cid", "file_name", b"file_name"]) -> None: ...

global___IPCFileDownloadChunkCreateRequest = IPCFileDownloadChunkCreateRequest

@typing.final
class IPCFileDownloadChunkCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class BlockDownload(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CID_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        NODE_ADDRESS_FIELD_NUMBER: builtins.int
        NODE_ID_FIELD_NUMBER: builtins.int
        PERMIT_FIELD_NUMBER: builtins.int
        cid: builtins.str
        size: builtins.int
        node_address: builtins.str
        node_id: builtins.str
        permit: builtins.str
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            size: builtins.int = ...,
            node_address: builtins.str = ...,
            node_id: builtins.str = ...,
            permit: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["cid", b"cid", "node_address", b"node_address", "node_id", b"node_id", "permit", b"permit", "size", b"size"]) -> None: ...

    BLOCKS_FIELD_NUMBER: builtins.int
    @property
    def blocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IPCFileDownloadChunkCreateResponse.BlockDownload]: ...
    def __init__(
        self,
        *,
        blocks: collections.abc.Iterable[global___IPCFileDownloadChunkCreateResponse.BlockDownload] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blocks", b"blocks"]) -> None: ...

global___IPCFileDownloadChunkCreateResponse = IPCFileDownloadChunkCreateResponse

@typing.final
class IPCFileDownloadBlockRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHUNK_CID_FIELD_NUMBER: builtins.int
    CHUNK_INDEX_FIELD_NUMBER: builtins.int
    BLOCK_CID_FIELD_NUMBER: builtins.int
    BLOCK_INDEX_FIELD_NUMBER: builtins.int
    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    chunk_cid: builtins.str
    chunk_index: builtins.int
    block_cid: builtins.str
    block_index: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        chunk_cid: builtins.str = ...,
        chunk_index: builtins.int = ...,
        block_cid: builtins.str = ...,
        block_index: builtins.int = ...,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "block_cid", b"block_cid", "block_index", b"block_index", "bucket_name", b"bucket_name", "chunk_cid", b"chunk_cid", "chunk_index", b"chunk_index", "file_name", b"file_name"]) -> None: ...

global___IPCFileDownloadBlockRequest = IPCFileDownloadBlockRequest

@typing.final
class IPCFileListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "bucket_name", b"bucket_name"]) -> None: ...

global___IPCFileListRequest = IPCFileListRequest

@typing.final
class IPCFileListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class IPCFile(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ROOT_CID_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        ENCODED_SIZE_FIELD_NUMBER: builtins.int
        CREATED_AT_FIELD_NUMBER: builtins.int
        root_cid: builtins.str
        name: builtins.str
        encoded_size: builtins.int
        @property
        def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            root_cid: builtins.str = ...,
            name: builtins.str = ...,
            encoded_size: builtins.int = ...,
            created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "encoded_size", b"encoded_size", "name", b"name", "root_cid", b"root_cid"]) -> None: ...

    LIST_FIELD_NUMBER: builtins.int
    @property
    def list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IPCFileListResponse.IPCFile]: ...
    def __init__(
        self,
        *,
        list: collections.abc.Iterable[global___IPCFileListResponse.IPCFile] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["list", b"list"]) -> None: ...

global___IPCFileListResponse = IPCFileListResponse

@typing.final
class IPCFileDeleteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSACTION_FIELD_NUMBER: builtins.int
    BUCKET_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    transaction: builtins.bytes
    bucket_name: builtins.bytes
    name: builtins.str
    def __init__(
        self,
        *,
        transaction: builtins.bytes = ...,
        bucket_name: builtins.bytes = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "name", b"name", "transaction", b"transaction"]) -> None: ...

global___IPCFileDeleteRequest = IPCFileDeleteRequest

@typing.final
class IPCFileDeleteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___IPCFileDeleteResponse = IPCFileDeleteResponse
