"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class BucketCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___BucketCreateRequest = BucketCreateRequest

@typing.final
class BucketCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "name", b"name"]) -> None: ...

global___BucketCreateResponse = BucketCreateResponse

@typing.final
class BucketViewRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name"]) -> None: ...

global___BucketViewRequest = BucketViewRequest

@typing.final
class BucketViewResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "name", b"name"]) -> None: ...

global___BucketViewResponse = BucketViewResponse

@typing.final
class BucketListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___BucketListRequest = BucketListRequest

@typing.final
class BucketListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Bucket(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        CREATED_AT_FIELD_NUMBER: builtins.int
        name: builtins.str
        @property
        def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "name", b"name"]) -> None: ...

    BUCKETS_FIELD_NUMBER: builtins.int
    @property
    def buckets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BucketListResponse.Bucket]: ...
    def __init__(
        self,
        *,
        buckets: collections.abc.Iterable[global___BucketListResponse.Bucket] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["buckets", b"buckets"]) -> None: ...

global___BucketListResponse = BucketListResponse

@typing.final
class BucketDeleteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___BucketDeleteRequest = BucketDeleteRequest

@typing.final
class BucketDeleteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___BucketDeleteResponse = BucketDeleteResponse

@typing.final
class FileBlockData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    CID_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    cid: builtins.str
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        cid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cid", b"cid", "data", b"data"]) -> None: ...

global___FileBlockData = FileBlockData

@typing.final
class StreamFileUploadCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "file_name", b"file_name"]) -> None: ...

global___StreamFileUploadCreateRequest = StreamFileUploadCreateRequest

@typing.final
class StreamFileUploadCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    stream_id: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        stream_id: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "created_at", b"created_at", "file_name", b"file_name", "stream_id", b"stream_id"]) -> None: ...

global___StreamFileUploadCreateResponse = StreamFileUploadCreateResponse

@typing.final
class Chunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Block(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CID_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        cid: builtins.str
        size: builtins.int
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            size: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["cid", b"cid", "size", b"size"]) -> None: ...

    STREAM_ID_FIELD_NUMBER: builtins.int
    CID_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    BLOCKS_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    cid: builtins.str
    index: builtins.int
    size: builtins.int
    @property
    def blocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Chunk.Block]: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        cid: builtins.str = ...,
        index: builtins.int = ...,
        size: builtins.int = ...,
        blocks: collections.abc.Iterable[global___Chunk.Block] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blocks", b"blocks", "cid", b"cid", "index", b"index", "size", b"size", "stream_id", b"stream_id"]) -> None: ...

global___Chunk = Chunk

@typing.final
class StreamFileUploadChunkCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHUNK_FIELD_NUMBER: builtins.int
    @property
    def chunk(self) -> global___Chunk: ...
    def __init__(
        self,
        *,
        chunk: global___Chunk | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["chunk", b"chunk"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["chunk", b"chunk"]) -> None: ...

global___StreamFileUploadChunkCreateRequest = StreamFileUploadChunkCreateRequest

@typing.final
class StreamFileUploadChunkCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class BlockUpload(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CID_FIELD_NUMBER: builtins.int
        NODE_ADDRESS_FIELD_NUMBER: builtins.int
        NODE_ID_FIELD_NUMBER: builtins.int
        PERMIT_FIELD_NUMBER: builtins.int
        cid: builtins.str
        node_address: builtins.str
        node_id: builtins.str
        permit: builtins.str
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            node_address: builtins.str = ...,
            node_id: builtins.str = ...,
            permit: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["cid", b"cid", "node_address", b"node_address", "node_id", b"node_id", "permit", b"permit"]) -> None: ...

    BLOCKS_FIELD_NUMBER: builtins.int
    @property
    def blocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StreamFileUploadChunkCreateResponse.BlockUpload]: ...
    def __init__(
        self,
        *,
        blocks: collections.abc.Iterable[global___StreamFileUploadChunkCreateResponse.BlockUpload] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blocks", b"blocks"]) -> None: ...

global___StreamFileUploadChunkCreateResponse = StreamFileUploadChunkCreateResponse

@typing.final
class StreamFileBlockData(google.protobuf.message.Message):
    """TODO: do not reuse this message for upload and download, create seprate messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    CID_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    CHUNK_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    cid: builtins.str
    """only present in first msg of request stream"""
    index: builtins.int
    """only present in first msg of request stream"""
    @property
    def chunk(self) -> global___Chunk:
        """only present in first msg of request stream"""

    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        cid: builtins.str = ...,
        index: builtins.int = ...,
        chunk: global___Chunk | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["chunk", b"chunk"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["chunk", b"chunk", "cid", b"cid", "data", b"data", "index", b"index"]) -> None: ...

global___StreamFileBlockData = StreamFileBlockData

@typing.final
class StreamFileUploadBlockResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StreamFileUploadBlockResponse = StreamFileUploadBlockResponse

@typing.final
class StreamFileUploadCommitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    ROOT_CID_FIELD_NUMBER: builtins.int
    CHUNK_COUNT_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    root_cid: builtins.str
    chunk_count: builtins.int
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        root_cid: builtins.str = ...,
        chunk_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chunk_count", b"chunk_count", "root_cid", b"root_cid", "stream_id", b"stream_id"]) -> None: ...

global___StreamFileUploadCommitRequest = StreamFileUploadCommitRequest

@typing.final
class StreamFileUploadCommitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    BUCKET_NAME_FIELD_NUMBER: builtins.int
    ENCODED_SIZE_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    COMMITTED_AT_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    file_name: builtins.str
    bucket_name: builtins.str
    encoded_size: builtins.int
    size: builtins.int
    @property
    def committed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        file_name: builtins.str = ...,
        bucket_name: builtins.str = ...,
        encoded_size: builtins.int = ...,
        size: builtins.int = ...,
        committed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["committed_at", b"committed_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "committed_at", b"committed_at", "encoded_size", b"encoded_size", "file_name", b"file_name", "size", b"size", "stream_id", b"stream_id"]) -> None: ...

global___StreamFileUploadCommitResponse = StreamFileUploadCommitResponse

@typing.final
class StreamFileDownloadCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    ROOT_CID_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    root_cid: builtins.str
    """optional"""
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        root_cid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "file_name", b"file_name", "root_cid", b"root_cid"]) -> None: ...

global___StreamFileDownloadCreateRequest = StreamFileDownloadCreateRequest

@typing.final
class StreamFileDownloadCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Chunk(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CID_FIELD_NUMBER: builtins.int
        ENCODED_SIZE_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        cid: builtins.str
        encoded_size: builtins.int
        size: builtins.int
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            encoded_size: builtins.int = ...,
            size: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["cid", b"cid", "encoded_size", b"encoded_size", "size", b"size"]) -> None: ...

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    CHUNKS_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    stream_id: builtins.str
    @property
    def chunks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StreamFileDownloadCreateResponse.Chunk]: ...
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        stream_id: builtins.str = ...,
        chunks: collections.abc.Iterable[global___StreamFileDownloadCreateResponse.Chunk] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "chunks", b"chunks", "stream_id", b"stream_id"]) -> None: ...

global___StreamFileDownloadCreateResponse = StreamFileDownloadCreateResponse

@typing.final
class StreamFileDownloadRangeCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    START_INDEX_FIELD_NUMBER: builtins.int
    END_INDEX_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    start_index: builtins.int
    end_index: builtins.int
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        start_index: builtins.int = ...,
        end_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "end_index", b"end_index", "file_name", b"file_name", "start_index", b"start_index"]) -> None: ...

global___StreamFileDownloadRangeCreateRequest = StreamFileDownloadRangeCreateRequest

@typing.final
class StreamFileDownloadChunkCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    CHUNK_CID_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    chunk_cid: builtins.str
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        chunk_cid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chunk_cid", b"chunk_cid", "stream_id", b"stream_id"]) -> None: ...

global___StreamFileDownloadChunkCreateRequest = StreamFileDownloadChunkCreateRequest

@typing.final
class StreamFileDownloadChunkCreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class BlockDownload(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CID_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        NODE_ADDRESS_FIELD_NUMBER: builtins.int
        NODE_ID_FIELD_NUMBER: builtins.int
        PERMIT_FIELD_NUMBER: builtins.int
        cid: builtins.str
        size: builtins.int
        node_address: builtins.str
        node_id: builtins.str
        permit: builtins.str
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            size: builtins.int = ...,
            node_address: builtins.str = ...,
            node_id: builtins.str = ...,
            permit: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["cid", b"cid", "node_address", b"node_address", "node_id", b"node_id", "permit", b"permit", "size", b"size"]) -> None: ...

    BLOCKS_FIELD_NUMBER: builtins.int
    @property
    def blocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StreamFileDownloadChunkCreateResponse.BlockDownload]: ...
    def __init__(
        self,
        *,
        blocks: collections.abc.Iterable[global___StreamFileDownloadChunkCreateResponse.BlockDownload] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blocks", b"blocks"]) -> None: ...

global___StreamFileDownloadChunkCreateResponse = StreamFileDownloadChunkCreateResponse

@typing.final
class StreamFileDownloadChunkCreateResponseV2(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class BlockDownload(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class Akave(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            NODE_ID_FIELD_NUMBER: builtins.int
            NODE_ADDRESS_FIELD_NUMBER: builtins.int
            node_id: builtins.str
            node_address: builtins.str
            def __init__(
                self,
                *,
                node_id: builtins.str = ...,
                node_address: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["node_address", b"node_address", "node_id", b"node_id"]) -> None: ...

        @typing.final
        class Filecoin(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            SP_ADDRESS_FIELD_NUMBER: builtins.int
            sp_address: builtins.str
            def __init__(
                self,
                *,
                sp_address: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["sp_address", b"sp_address"]) -> None: ...

        CID_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        AKAVE_FIELD_NUMBER: builtins.int
        FILECOIN_FIELD_NUMBER: builtins.int
        cid: builtins.str
        size: builtins.int
        @property
        def akave(self) -> global___StreamFileDownloadChunkCreateResponseV2.BlockDownload.Akave: ...
        @property
        def filecoin(self) -> global___StreamFileDownloadChunkCreateResponseV2.BlockDownload.Filecoin: ...
        def __init__(
            self,
            *,
            cid: builtins.str = ...,
            size: builtins.int = ...,
            akave: global___StreamFileDownloadChunkCreateResponseV2.BlockDownload.Akave | None = ...,
            filecoin: global___StreamFileDownloadChunkCreateResponseV2.BlockDownload.Filecoin | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["akave", b"akave", "filecoin", b"filecoin"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["akave", b"akave", "cid", b"cid", "filecoin", b"filecoin", "size", b"size"]) -> None: ...

    BLOCKS_FIELD_NUMBER: builtins.int
    @property
    def blocks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StreamFileDownloadChunkCreateResponseV2.BlockDownload]: ...
    def __init__(
        self,
        *,
        blocks: collections.abc.Iterable[global___StreamFileDownloadChunkCreateResponseV2.BlockDownload] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["blocks", b"blocks"]) -> None: ...

global___StreamFileDownloadChunkCreateResponseV2 = StreamFileDownloadChunkCreateResponseV2

@typing.final
class StreamFileDownloadBlockRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    CHUNK_CID_FIELD_NUMBER: builtins.int
    CHUNK_INDEX_FIELD_NUMBER: builtins.int
    BLOCK_CID_FIELD_NUMBER: builtins.int
    BLOCK_INDEX_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    chunk_cid: builtins.str
    chunk_index: builtins.int
    block_cid: builtins.str
    block_index: builtins.int
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        chunk_cid: builtins.str = ...,
        chunk_index: builtins.int = ...,
        block_cid: builtins.str = ...,
        block_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["block_cid", b"block_cid", "block_index", b"block_index", "chunk_cid", b"chunk_cid", "chunk_index", b"chunk_index", "stream_id", b"stream_id"]) -> None: ...

global___StreamFileDownloadBlockRequest = StreamFileDownloadBlockRequest

@typing.final
class StreamFileListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name"]) -> None: ...

global___StreamFileListRequest = StreamFileListRequest

@typing.final
class File(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: builtins.int
    ROOT_CID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ENCODED_SIZE_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    COMMITED_AT_FIELD_NUMBER: builtins.int
    stream_id: builtins.str
    root_cid: builtins.str
    name: builtins.str
    encoded_size: builtins.int
    size: builtins.int
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def commited_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        stream_id: builtins.str = ...,
        root_cid: builtins.str = ...,
        name: builtins.str = ...,
        encoded_size: builtins.int = ...,
        size: builtins.int = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        commited_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["commited_at", b"commited_at", "created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["commited_at", b"commited_at", "created_at", b"created_at", "encoded_size", b"encoded_size", "name", b"name", "root_cid", b"root_cid", "size", b"size", "stream_id", b"stream_id"]) -> None: ...

global___File = File

@typing.final
class StreamFileListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILES_FIELD_NUMBER: builtins.int
    @property
    def files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___File]: ...
    def __init__(
        self,
        *,
        files: collections.abc.Iterable[global___File] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["files", b"files"]) -> None: ...

global___StreamFileListResponse = StreamFileListResponse

@typing.final
class StreamFileViewRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "file_name", b"file_name"]) -> None: ...

global___StreamFileViewRequest = StreamFileViewRequest

@typing.final
class StreamFileViewResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    STREAM_ID_FIELD_NUMBER: builtins.int
    ROOT_CID_FIELD_NUMBER: builtins.int
    ENCODED_SIZE_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    COMMITTED_AT_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    stream_id: builtins.str
    root_cid: builtins.str
    encoded_size: builtins.int
    size: builtins.int
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def committed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
        stream_id: builtins.str = ...,
        root_cid: builtins.str = ...,
        encoded_size: builtins.int = ...,
        size: builtins.int = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        committed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["committed_at", b"committed_at", "created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "committed_at", b"committed_at", "created_at", b"created_at", "encoded_size", b"encoded_size", "file_name", b"file_name", "root_cid", b"root_cid", "size", b"size", "stream_id", b"stream_id"]) -> None: ...

global___StreamFileViewResponse = StreamFileViewResponse

@typing.final
class StreamFileDeleteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "file_name", b"file_name"]) -> None: ...

global___StreamFileDeleteRequest = StreamFileDeleteRequest

@typing.final
class StreamFileDeleteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StreamFileDeleteResponse = StreamFileDeleteResponse

@typing.final
class StreamFileListVersionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_NAME_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    bucket_name: builtins.str
    file_name: builtins.str
    def __init__(
        self,
        *,
        bucket_name: builtins.str = ...,
        file_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket_name", b"bucket_name", "file_name", b"file_name"]) -> None: ...

global___StreamFileListVersionsRequest = StreamFileListVersionsRequest

@typing.final
class StreamFileListVersionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSIONS_FIELD_NUMBER: builtins.int
    @property
    def versions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___File]: ...
    def __init__(
        self,
        *,
        versions: collections.abc.Iterable[global___File] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["versions", b"versions"]) -> None: ...

global___StreamFileListVersionsResponse = StreamFileListVersionsResponse
